version: "3"
services:
  go-media-organizer:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./data:/app/data
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: test
  bash:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    entrypoint: ["bash", "-c"]
    command: ["ls", "/usr/local/bin"]
    volumes:
      - ./data:/app/data
